---
- name: Ensure firewalld is installed
  yum:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open required ports in the firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ firewall_allowed_ports }}"
