name "complex_webapp"
version "3.2.1"
chef_version ">= 15.0"
description "Deploys a full web app stack with DB, SSL, monitoring"
maintainer "Platform Team"
license "Apache-2.0"
depends "nginx"
depends "postgresql"
depends "prometheus"
supports "ubuntu"
