name 'nginx_firewall'
maintainer 'Your Name'
maintainer_email 'you@example.com'
license 'Apache-2.0'
description 'Installs/Configures nginx and firewall rules for HTTP'
version '0.1.0'
chef_version '>= 14.0'
depends 'firewalld', '>= 3.0'
